# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Map secret variable as environment variable
- bash: |
    echo "export MY_SECRET_VARIABLE=$MY_SECRET_VARIABLE_VALUE" >> $(Agent.BuildDirectory)/.env
  env:
    MY_SECRET_VARIABLE_VALUE: $(gmail_app_pwd)
  displayName: 'Map secret variable'

- script: python main.py
  env:
    gmail_app_pwd: $(MY_SECRET_VARIABLE)

- script: python main.py
