# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "39 16 * * *"
  displayName: Daily 10:39 AM MT trigger
  branches:
    include:
    - main

trigger: none

pool:
  vmImage: ubuntu-latest


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Map secret variables as environment variables
- bash: |
    echo "export gmail_app_pwd=$gmail_app_pwd" >> $(Agent.BuildDirectory)/.env
    echo "export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $(Agent.BuildDirectory)/.env
    
  env:
    gmail_app_pwd: $(gmail_app_pwd)
    GOOGLE_APPLICATION_CREDENTIALS: $(GOOGLE_APPLICATION_CREDENTIALS)

  displayName: 'Map secret variables'
  


- script: python main.py
  env:
    gmail_app_pwd: $(gmail_app_pwd)
    GOOGLE_APPLICATION_CREDENTIALS: $(GOOGLE_APPLICATION_CREDENTIALS)


